version: '3'
services:
  app:
    build: .
    container_name: oli_app
    ports:
      - 4000:4000
    env_file: ./oli.env
    depends_on:
      - postgres
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/assets/node_modules

  postgres:
    image: postgres
    container_name: oli_postgres
    ports:
      - 5432:5432
    env_file: ./postgres.env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # ngrok:
  #   container_name: oli_ngrok

volumes:
  postgres_data: