name: Elixir CI on Branch Push

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Configuration
      run: cp oli.example.env oli.env && cp postgres.example.env postgres.env
    - name: Start Test Database
      run: docker-compose up -d postgres
    - name: Setup elixir
      uses: actions/setup-elixir@v1
      with:
        elixir-version: 1.5 # Define the elixir version [required]
        otp-version: 22.2 # Define the OTP version [required]
    - name: Install Dependencies
      run: mix deps.get
    - name: Run Tests
      run: mix test
